---
server:
  port: 9002

security:
  basic:
    enabled: false

spring:
  datasource:
    url: ${oauth.database.url}  #your database url. Replace "xxx.x.x.x" with your ip address.
    username: ${oauth.database.username} #database schema user name
    password: ${oauth.database.password} #database schema password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
  cloud:
    consul:
      host: ${consul.host}
      port: ${consul.port}
  application:
    name: amisoft-api-gateway


management:
  security:
    enabled: false


zuul:
  routes:
    amisoft:
         path: /amisoft/**
         serviceId: amisoft-secure-resource





spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect